### ISSUE TITLE
changing columns in src_smartrecruiters__applications and src_smartrecruiters__applicants

### ISSUE THREAD

**Issue by cristinabaldor** [TEAMSchools/teamster#1336]
These are the new columns coming from the report, can we remove any that aren't these from the src tables?

applications:
            application_id,
            candidate_id,
            department_internal,
            job_title,
            job_city,
            recruiters,
            application_field_phone_interview_score as phone_interview_score,
            application_field_resume_score as resume_score,
            application_reason_for_rejection as reason_for_rejection,
            application_reason_for_withdrawal as reason_for_withdrawal,
            application_status,
            application_state_hired_date 
            application_state_new_date 
            application_state_offer_date as timestamp
            application_state_rejected_date
            application_status_interview_demo_date 
            application_status_interview_phone_screen_complete_date 
            application_status_interview_phone_screen_requested_date 

applicants:
            candidate_id,
            *ADD* candidate_first_last,
            candidate_first_name,
            candidate_last_name,
            *ADD* candidate_source,
            *ADD* candidate_source_type,
            *ADD* candidate_source_subtype,
            candidate_email,
            application_field_school_shared_with_new_jersey,
            application_field_school_shared_with_miami,
            screening_question_answer_new_jersey_undergrad_gpa,
            screening_question_answer_new_jersey_grad_gpa,
            screening_question_answer_new_jersey_teacher_certification_question,
            screening_question_answer_new_jersey_out_of_state_teacher_certification_details,
            screening_question_answer_new_jersey_out_of_state_teacher_certification_sped_credits,
            screening_question_answer_new_jersey_out_of_state_sped_credits,
            screening_question_answer_miami_undergrad_gpa,
            screening_question_answer_miami_grad_gpa,
            screening_question_answer_miami_teacher_certification_question,
            screening_question_answer_miami_teacher_certification_endorsement_question,
            screening_question_answer_miami_out_of_state_teaching_certification_details,
            screening_question_answer_new_jersey_miami_affiliated_orgs,
            screening_question_answer_new_jersey_miami_other_orgs,
            screening_question_answer_new_jersey_miami_current_or_former_kipp_employee,
            screening_question_answer_new_jersey_miami_current_or_former_kipp_nj_miami_employee,
            screening_question_answer_new_jersey_miami_expected_salary,
            screening_question_answer_new_jersey_miami_how_did_you_hear_about_kipp_nj_miami,
            screening_question_answer_national_race,
            screening_question_answer_national_gender,
            screening_question_answer_national_are_you_alumnus,
            screening_question_answer_national_in_which_regions_alumnus

**Comment by cbini** [comment]
@cbaldor I added a new column to applications this morning. The rest have to stay, but you can remove them from staging if you'd like
