### ISSUE TITLE
New PS Tables for Grad Plan tracking

### ISSUE THREAD

**Issue by GabyRangelB** [TEAMSchools/teamster#1354]
Howdy!

We are planning to add student progress towards completing their grad plan to the Early Warning Dashboard. I did some digging on the PS user group and found a few people who have already done this. They listed the following tables. Could we bring these over to BQ, please? I'll attach the sample SQL code to the Asana task.

Thanks!

1. gpprogresssubject
2. GPPROGRESSSUBJECTWAIVED
3. gpnode
4. gpnode gpnodeTopLevel
5. gpversion
6. gradplan
7. GPSTUDENTWAIVER

**Comment by anthonygwalters** [comment]
@cbini riding Gaby's coattails here - can you also add **UsersCoreFields** please? I need it for the course teacher submission

**Comment by cbini** [comment]
@GabyRangelB do we need these for all regions?

**Comment by GabyRangelB** [comment]
NJ only rn. tks!
