### ISSUE TITLE
School year field for DIBELS PM Lookup

### ISSUE THREAD

**Issue by GabyRangelB** [TEAMSchools/teamster#1761]
Hey! Can we add an academic year field to the DIBELS PM Lookup table coming from the [Assessments G-Sheet](https://docs.google.com/spreadsheets/d/1G2z9rwXsFaMdFL6iOYdfQTVjZ7bctXMyz_Q09IhP4QE/edit?gid=1455973435#gid=1455973435), please? 

And rename the column Measure Name to Measure Level Code?

Thanks!

**Comment by GabyRangelB** [comment]
Gonna need a few changes for the new PM model, so I'll just add them all here. In addition to the SY one, I also need to do 2 things to this [DIBELS Measures tab](https://docs.google.com/spreadsheets/d/1G2z9rwXsFaMdFL6iOYdfQTVjZ7bctXMyz_Q09IhP4QE/edit?gid=1867365060#gid=1867365060):

1. Add a new column B called Measure Name
2. Rename the current column Name to Measure Standard

This will break the Deanslist DIBELS data, so before it becomes live, can you let me know please so I can quickly fix that as well so it doesn't impact anyone?

Thanks!

**Comment by cbini** [comment]
from #1776 

>Hey, can we add a new Boolean column to the Course/Subject Crosswalk tab of the Assessments G-sheet, called "Exclude from Gradebook"
