### ISSUE TITLE
kippcamden missing as `_dbt_source_relation` on all kipptaf i-Ready tables

### ISSUE THREAD

**Issue by anthonygwalters** [TEAMSchools/teamster#2075]
Only kippmiami and kippnewark are appearing - Camden schools/students are still there, but are appearing under kippnewark. I removed the union join clause from `int_reporting__student_filters` as a temporary workaround.

**Comment by anthonygwalters** [comment]
#2074

**Comment by cbini** [comment]
@anthonygwalters this is actually expected. iReady rolls up Newark and Camden together, and they show up on a `kippnj_iready` dataset. Removing the dataset join is the fix, but we may want to consider spoofing their correct regional dataset
