### ISSUE TITLE
Subject, discipline, credit type crosswalk

### ISSUE THREAD

**Issue by GabyRangelB** [TEAMSchools/teamster#424]
Create a way to crosswalk discipline to subject to credit type to align them so we can join tables easier (i.e. Discipline is ELA, subjects can be ELA 11 or Reading 3, and credit type is ENG). Can be used for aligning these across assessments, too.

**Comment by cbini** [comment]
https://github.com/TEAMSchools/teamster/blob/c5c74f6ed3490022d4177c70579abef99abc17ef/src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql#L140

**Comment by cbini** [comment]
```
with
    subjects as (
        select
            subject as iready_subject,
            case
                subject when 'Reading' then 'Text Study' when 'Math' then 'Mathematics'
            end as illuminate_subject_area,
            case
                subject when 'Reading' then 'ENG' when 'Math' then 'MATH'
            end as powerschool_credittype,
        from unnest(['Reading', 'Math']) as subject
    ),
```
