### ISSUE TITLE
NULLs in fields coming from applicants source in smartrecruiter

### ISSUE THREAD

**Issue by cristinabaldor** [TEAMSchools/teamster#433]
Applicant table (demographic info) data is null coming from [src/dbt/kipptaf/models/smartrecruiters/sources.yml](url). Recruitment team also wants to add a new field called performance task status.

**Comment by cbini** [comment]
https://github.com/TEAMSchools/teamster/blob/b4c4d42c5ff9073172d16ed847969cd5911bd7f4/src/dbt/kipptaf/models/smartrecruiters/sources.yml#L9-L14

**Comment by cbini** [comment]
report columns are all different, need to update schema

https://github.com/TEAMSchools/teamster/blob/719eb3fb653ebc34e7b99255d28632d2f87a3b1e/src/teamster/core/smartrecruiters/schema.py
