### ISSUE TITLE
Correct school year value for FSA

### ISSUE THREAD

**Issue by GabyRangelB** [TEAMSchools/teamster#437]
This query

select distinct school_year
from `teamster-332318.kippmiami_fldoe.stg_fldoe__fsa`

yields 2021 and 2122:

![image](https://github.com/TEAMSchools/teamster/assets/140853376/4782dd4a-55f6-485c-86ba-5820fc1eb441)

Can we get it fixed, please?

Thanks!

**Comment by cbini** [comment]
Use `academic_year`. `school_year` is a raw field coming in from the source file.

https://github.com/TEAMSchools/teamster/blob/235d12f425fefb077d3cafe4bd77cb01da00f6ee/src/dbt/kippmiami/models/fldoe/staging/stg_fldoe__fsa.sql#L65

**Comment by GabyRangelB** [comment]
Oh, wait, is that how they say 2020-2021 and 2021-2022?! Yikes! OK. I'll keep that in mind.

**Comment by cbini** [comment]
yeah it's an abbreviation
