### ISSUE TITLE
Replace student measure level with tested out or discontinued, if it exists

### ISSUE THREAD

**Issue by cbini** [TEAMSchools/teamster#489]
For `int_amplify__benchmark_student_summary_unpivot` can we make it so that if a student has tested out or discontinued, their measure level is replaced by "Tested Out" when tested out, "Discontinued" when discontinued, and if they are have NOT tested out or discontinued, then we use the measure level they earned. Thank you!

**Comment by cbini** [comment]
@GabyRangelB wanted to check if this was still wanted. I can make this change this week.

**Comment by GabyRangelB** [comment]
Still needed. Please and thank you!
