### ISSUE TITLE
Add questions to Career Launch Pivot

### ISSUE THREAD

**Issue by CGibson17** [TEAMSchools/teamster#503]
Please add any/all questions to the pivot that answer the question of what the alumni does for a living. Thanks!

**Comment by cbini** [comment]
https://github.com/TEAMSchools/teamster/blob/cbe33efcc0641aaa7f9cb1cfc38a3483d80c2e48/src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql#L93-L121
