### ISSUE TITLE
Delete `rpt_tableau__state_assessment_dashboard`

### ISSUE THREAD

**Issue by GabyRangelB** [TEAMSchools/teamster#504]
Hey! Not sure how to do this to preserve historic views. Can we please archive or delete this view: teamster-332318.kipptaf_tableau.rpt_tableau__state_assessment_dashboard? Thank you!

**Comment by cbini** [comment]
You can just open a PR to delete the file to remove it. 

Did this new view get created with the wrong name by mistake? https://github.com/TEAMSchools/teamster/blob/main/src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

If so, you can overwrite the one with the new code and delete the new one.

**Comment by GabyRangelB** [comment]
Ah! That's easy!

No. Walters added that view for you to create so he could migrate the state assessment dash from gabby to DBT. However, I took over the project and we decided to go on a different direction and I ended up creating a new view. I confirmed with him today what he wanted to do with the migrated view and he said we could remove it. Opening the PR right now.

**Comment by cbini** [comment]
Are you starting fresh with the data source in Tableau? If not, you could just overwrite the existing one and keep the same connection.

**Comment by GabyRangelB** [comment]
I created a new one with a similar name but it says 'assessmentS' instead of 'assessment.'
