### ISSUE TITLE
Creating Snapshot/Lockbox Row Versioning for SMG observations

### ISSUE THREAD

**Issue by cristinabaldor** [TEAMSchools/teamster#515]
fields that we need to monitor for changes and exclude based on snapshot dates in observations:

```
SELECT
  observation_id,
  rubric_name,
  score,
  created,
  first_published,
  last_modified,
  last_published,
  observed_at
FROM
  `teamster-332318.kipptaf_schoolmint_grow.stg_schoolmint_grow__observations`
WHERE
  rubric_name LIKE '%ETR%'
```

```
SELECT
  observation_id,
  last_modified,
  measurement,
  value_score
FROM
  `teamster-332318.kipptaf_schoolmint_grow.stg_schoolmint_grow__observations__observation_scores`
```

**Comment by cristinabaldor** [comment]
Hey @cbini, I'm fuzzy on our talk about creating snapshots so let me know if you need more info. This is what I think we would need to just monitor PM observations for changes and add a 'valid on' date for filtering in src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

**Comment by cristinabaldor** [comment]
Reopening to add an end date field so that we can join on where the lockbox date is between the valid dates for a record.

**Comment by cbini** [comment]
@cristinabaldor just want to clarify: do these fields need to be tracked on the snapshot too?
- `created`
- `first_published`
- `last_published`
- `observed_at`

**Comment by cristinabaldor** [comment]
i think the only thing we have to monitor for a change is value_score, as long as we can tie that to the observation_id the rest should stay the same
