### ISSUE TITLE
GPA term issue with Florida students

### ISSUE THREAD

**Issue by anthonygwalters** [TEAMSchools/teamster#516]
Y1 GPAs don't seem to be tracking along with term GPAs - example [linked here](https://console.cloud.google.com/bigquery?sq=624231820004:c25a60346c184caa831ee63ef65ba1c7).

**Comment by cbini** [comment]
https://github.com/TEAMSchools/teamster/blob/76a96360c5097dd835bf84b7f00431b72b70625a/src/dbt/powerschool/models/intermediate/int_powerschool__gpa_term.sql#L99-L111

**Comment by cbini** [comment]
@anthonygwalters this is just an odd artifact of the student not having Q2 grades for some courses that they took in Q1. Their Q2 term GPA is lower because the grades they _do_ have in Q2 are on average than their overall Y1 average, which includes all Q1 courses.
