### ISSUE TITLE
Extra view still present on BQ

### ISSUE THREAD

**Issue by GabyRangelB** [TEAMSchools/teamster#538]
Hey! So, I submitted a PR a while back to remove 

![image](https://github.com/TEAMSchools/teamster/assets/140853376/553586e1-6684-4471-ae09-abebecd9479a)

because it has been replaced and no longer in use. However, it still shows on BQ even though it is not on main on DBT:

![image](https://github.com/TEAMSchools/teamster/assets/140853376/edaa6880-36d6-4eed-b64f-b479e066248b)

rpt_state_assessmentS is good to stay. rpt_state_assessment should go from BQ.

Thanks!

**Comment by cbini** [comment]
just dropped it
