### ISSUE TITLE
checking multiple choice grid questions

### ISSUE THREAD

**Issue by cristinabaldor** [TEAMSchools/teamster#548]
hey @cbini , can we check whether this type of question is in `base_google_forms__form_responses` ? we should have a bunch of answers like this from the KTAF Support Survey but they are all coming in null

![Screenshot 2024-01-23 at 1 03 24 PM](https://github.com/TEAMSchools/teamster/assets/68877416/e81e400b-71c2-4997-8b18-d4fbf1974650)

**Comment by cbini** [comment]
will do. probably has a different question model or something
