### ISSUE TITLE
Add a "Discipline" column to src_assessments__course_subject_crosswalk

### ISSUE THREAD

**Issue by anthonygwalters** [TEAMSchools/teamster#559]
Right now, HS subject areas (ie. English 100, Geometry, etc.) are grouped in Tableau, so it's not easy to join data points that are just "ELA" or "Math" to those subject areas without complex case-statement-based joins.

**Comment by cbini** [comment]
would this be solved by adding credittype to the tableau view?

**Comment by anthonygwalters** [comment]
yeah that might work - let me try it & get back to you
