### ISSUE TITLE
Can we add is_cur_term to base_powerscool__final_grades, please?

### ISSUE THREAD

**Issue by GabyRangelB** [TEAMSchools/teamster#789]
Hi!

Working on the gradebook dash revamp - trying to reduce the number of rows. It would help me out to add:

```
            if(
                current_date('America/New_York')
                between termbin_start_date and termbin_end_date,
                1,
                0
            ) as is_curterm,
```

to base_powerschool_final_grades. I was going to do a PR for it, but I dont think I have access to the region-specific code that makes up kipptaf_powerschool.base_powerschool__final_grades.

Thank you!

**Comment by cbini** [comment]
Could your thinking some more? The row count is already limited by academic year on the main select statement:

https://github.com/TEAMSchools/teamster/blob/f0bf64e6cf55f7f47fdaa38e3f42ad0825000d37/src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_dashboard.sql#L205

and `is_curterm` is already applied where needed

https://github.com/TEAMSchools/teamster/blob/f0bf64e6cf55f7f47fdaa38e3f42ad0825000d37/src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_dashboard.sql#L281

**Comment by GabyRangelB** [comment]
> Could your thinking some more? The row count is already limited by academic year on the main select statement:
> 
> https://github.com/TEAMSchools/teamster/blob/f0bf64e6cf55f7f47fdaa38e3f42ad0825000d37/src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_dashboard.sql#L205
> 
> and `is_curterm` is already applied where needed
> 
> https://github.com/TEAMSchools/teamster/blob/f0bf64e6cf55f7f47fdaa38e3f42ad0825000d37/src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_dashboard.sql#L281

Hey!

The gr.is_curterm comes from the CTE called final_grades. The CTE final_grades comes from base_powerschool__final_grades. From what I see, the final_grades CTE was created just so that is_curterm could be created to be used later. For example, gr.is_curterm then drives the proper use of need_60, need_70, need_80 and need_90 later by doing:

```
    max(case when gr.is_curterm = 1 then gr.need_60 end) over (
        partition by co.student_number, co.academic_year, gr.course_number
    ) as need_65,
    max(case when gr.is_curterm = 1 then gr.need_70 end) over (
        partition by co.student_number, co.academic_year, gr.course_number
    ) as need_70,
    max(case when gr.is_curterm = 1 then gr.need_80 end) over (
        partition by co.student_number, co.academic_year, gr.course_number
    ) as need_80,
    max(case when gr.is_curterm = 1 then gr.need_90 end) over (
        partition by co.student_number, co.academic_year, gr.course_number
    ) as need_90,
```

The final_grade CTE seems unnecessary to me if its only point is to create an is_curterm field. I saw that `kipptaf_powerschool`.`int_powerschool__category_grades` has a default is_current, so it made sense to me that base_powerschool_final_grades to have one as well.

My goal is to streamline these calculations, change the data model for the gradebook dash from long to wide, and merging the three queries that make up the Gradebook dash into one wide table to meet the requests of the users. LMK if showing you the draft new query would help understand the vision that is driving me to ask for this change. Thanks!

**Comment by cbini** [comment]
Ok yeah, I get it now. Thanks! The courses join is unnecessary too, looking at `base_powerschool__final_grades`
