### ISSUE TITLE
Create Microgoals Source/Staging Table

### ISSUE THREAD

**Issue by cristinabaldor** [TEAMSchools/teamster#793]
Can we make this a table in Teamster?

https://docs.google.com/spreadsheets/d/1TC3QYDq9cAnNJs27xeX9_E55L80D6uoVKS6taW9ojaw/edit#gid=0

**Comment by cbini** [comment]
I think this might be available via `kipptaf_schoolmint_grow.stg_schoolmint_grow__rubrics`

**Comment by cbini** [comment]
seeing 12 goals that might not be set up correctly on schoolmint. can we check these out?
```
select *
from dbt_cloud_pr_440244_817_schoolmint_grow.stg_schoolmint_grow__microgoals
where goal_description is null
```

**Comment by cristinabaldor** [comment]
hey this looks perfect, thank you so much. I just fixed those 12 tags in Grow.

**Comment by cbini** [comment]
@cristinabaldor can you double check `3C.05`? the rest look ok now

**Comment by cristinabaldor** [comment]
just tagged it again

**Comment by cristinabaldor** [comment]
hey @cbini can we take another look at how the tag_ids are coming over? I think there's a mismatch somehow. For microgoal 2C.02 What to Do, tag_id from `stg_schoolmint_grow__generic_tags` and `stg_schoolmint_grow__assignments` is '64b559d62c95f30011faeee5', tag on `stg_schoolmint_grow__microgoals` is '64b1789edebb8800120613fb'. i think it has to do with the weird nesting.


![image](https://github.com/TEAMSchools/teamster/assets/68877416/50295d9a-c304-4b31-9b43-4baf7a2fc35b)

![image](https://github.com/TEAMSchools/teamster/assets/68877416/b2dec58a-5b31-42da-952e-e9f25aa9cd31)

**Comment by cbini** [comment]
Weird, it looks like the base-level tag is the description, but the one tagged to the assignments is the goal label.

**Comment by cbini** [comment]
this should fix it: https://github.com/TEAMSchools/teamster/commit/21053153c5e12add967cfb6d81588abea08f5f8a
